# Generated by Django 3.2.6 on 2021-09-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_car_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('enabled_widgets', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
