# Generated by Django 3.2.6 on 2021-10-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210910_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cameras',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
