# Generated by Django 4.0.3 on 2022-04-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_camera_location_remove_profile_enabled_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
