# Generated by Django 4.0.3 on 2022-04-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_camera_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='direction',
            field=models.CharField(choices=[('1', 'Back'), ('2', 'Forward'), ('3', 'Left'), ('4', 'Right')], default='1', max_length=20),
        ),
    ]
