# Generated by Django 4.0.3 on 2022-04-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_camera_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='marker_type',
            new_name='location_type',
        ),
        migrations.AlterField(
            model_name='camera',
            name='direction',
            field=models.CharField(choices=[('BACK', 'Back'), ('FORWARD', 'Forward'), ('LEFT', 'Left'), ('RIGHT', 'Right')], default='1', max_length=20),
        ),
    ]
