# Generated by Django 4.0.3 on 2022-04-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_location_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile'),
        ),
    ]
