# Generated by Django 4.0.3 on 2022-04-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_location_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cameras',
        ),
        migrations.AlterField(
            model_name='camera',
            name='direction',
            field=models.CharField(choices=[('BACK', 'Back'), ('FORWARD', 'Forward'), ('LEFT', 'Left'), ('RIGHT', 'Right'), ('INTERIOR', 'Interior')], default='BACK', max_length=20),
        ),
    ]
