# Generated by Django 4.0.3 on 2022-04-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_profile_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device_id',
        ),
        migrations.AddField(
            model_name='camera',
            name='device_id',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
