# Generated by Django 4.0.3 on 2022-04-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_profile_cameras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cameras',
        ),
    ]
