# Generated by Django 4.0.3 on 2022-04-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_profile_cameras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='camera',
        ),
        migrations.AddField(
            model_name='profile',
            name='cameras',
            field=models.ManyToManyField(related_name='foo', to='dashboard.camera'),
        ),
    ]
