# Generated by Django 4.0.3 on 2022-04-09 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_profile_cameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_date',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='modified_date',
            field=models.TimeField(auto_now=True),
        ),
    ]
